name: CI/CD Push to Docker Hub

on:
  push:
    branches: [ "main" ] # Chạy khi bạn push code lên nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code từ GitHub về máy ảo
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Java 17 (Cần thiết để build file .jar)
      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          # Sử dụng bản build từ Oracle vì các bên khác có thể chưa cập nhật bản 25
          distribution: 'oracle' 
          cache: maven

      # Bước 3: Build dự án bằng Maven để tạo file .jar
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Bước 4: Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 5: Build Docker Image và Push lên Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Lưu ý: Thay 'user_docker' bằng tên thật hoặc dùng biến secret
          tags: ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
